TARGET = lib/libcomm.a

SRC_DIR_RECURSION = Y

SRC_FILE_DIRS += . 
INCLUDE += -I.
LIBS += 

NEED_MAKE_DEP = Y

include ../skynet/include.mk
include ../3rd/yac/yac.mk
include ../protocol/proto.mk
include ../mk/rules_inc.mk