TARGET = lib/libcomm.a

SRC_DIR_RECURSION = Y

SRC_FILE_DIRS += . 
INCLUDE += -I.
LIBS += 

NEED_MAKE_DEP = Y

include ../3rd/libxl-3.6.2.0/libxl.mk
include ../3rd/yac/yac.mk
include ../mk/rules_inc.mk