TARGET = lib/libxcutil.a

SRC_DIR_RECURSION = Y

SRC_FILE_DIRS += ./src 
INCLUDE += -I./include -I/usr/local/mysql/include
LIBS += -L/usr/local/mysql/lib/mysql -lmysqlclient

include ../../mk/rules_inc.mk
